# docker-compose.yml
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=trusted_interface
      - POSTGRES_DB=gw-backend
